# -*- coding: utf-8 -*-
"""da day2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IqH7cfRoX3ioS-sXA-SUuZj5uWsSelEC
"""

numerical data->histogram
catergorical ->countplot
bivariate analysis 2 cols
for numerical=x   hue(catergorical col)     histogram
catergorical -countplot
x=categorical          hue= catergorical     15 scatter plot,48 barplot

import matplotlib.pyplot as plt

import seaborn as sns

import pandas as pd

import numpy as np

sns.get_dataset_names()

df= sns.load_dataset("titanic")
df

plt.figure()
sns.scatterplot(x=df['age'],y=df['age'])
plt.show()

plt.figure()
sns.scatterplot(x=df['age'],y=df['fare'])
plt.show()



"""plt.show()
survived-age
        -sibsp
        -parch
        -fare
        -pclass
  age-sibap
  -oarch
  -fare
  -pclass
sibsp-parch
     -fare
     -pclass
     -fare
     -pclass
     -pclass
"""

plt.figure()
sns.scatterplot(x=df['survived'],y=df['age'])
plt.show()

plt.figure()
sns.scatterplot(x=df['survived'],y=df['sibsp'])
plt.show()

plt.figure()
sns.scatterplot(x=df['survived'],y=df['parch'])
plt.show()

plt.figure()
sns.scatterplot(x=df['survived'],y=df['fare'])
plt.show()

plt.figure()
sns.scatterplot(x=df['survived'],y=df['pclass'])
plt.show()

plt.figure()
sns.scatterplot(x=df['age'],y=df['sibsp'])
plt.show()

plt.figure()
sns.scatterplot(x=df['age'],y=df['parch'])
plt.show()

plt.figure()
sns.scatterplot(x=df['age'],y=df['fare'])
plt.show()

plt.figure()
sns.scatterplot(x=df['age'],y=df['pclass'])
plt.show()

plt.figure()
sns.scatterplot(x=df['sibsp'],y=df['parch'])
plt.show()

plt.figure()
sns.scatterplot(x=df['sibsp'],y=df['fare'])
plt.show()

plt.figure()
sns.scatterplot(x=df['sibsp'],y=df['pclass'])
plt.show()

plt.figure()
sns.scatterplot(x=df['sibsp'],y=df['fare'])
plt.show()

plt.figure()
sns.scatterplot(x=df['sibsp'],y=df['pclass'])
plt.show()

plt.figure()
sns.barplot(x=df['age'],y=df['sex'])
plt.show()

plt.figure()
sns.barplot(x=df['age'],y=df['embarked'])
plt.show()

plt.figure()
sns.barplot(x=df['age'],y=df['class'])
plt.show()

plt.figure()
sns.barplot(x=df['age'],y=df['sex'])
plt.show()

plt.figure()
sns.barplot(x=df['pclass'],y=df['embarked'])
plt.show()

plt.figure()
sns.barplot(x=df['pclass'],y=df['sex'])
plt.show()

plt.figure()
sns.barplot(x=df['pclass'],y=df['class'])
plt.show()

plt.figure()
sns.barplot(x=df['survived'],y=df['embarked'])
plt.show()

plt.figure()
sns.barplot(x=df['survived'],y=df['sex'])
plt.show()

plt.figure()
sns.barplot(x=df['survived'],y=df['class'])
plt.show()

plt.figure()
sns.barplot(x=df['sibsp'],y=df['sex'])
plt.show()

plt.figure()
sns.barplot(x=df['sibsp'],y=df['embarked'])
plt.show()

plt.figure()
sns.barplot(x=df['sibsp'],y=df['class'])
plt.show()

plt.figure()
sns.barplot(x=df['parch'],y=df['sex'])
plt.show()

plt.figure()
sns.barplot(x=df['parch'],y=df['class'])
plt.show()

plt.figure()
sns.barplot(x=df['parch'],y=df['embarked'])
plt.show()

plt.figure()
sns.barplot(x=df['fare'],y=df['sex'])
plt.show()

plt.figure()
sns.barplot(x=df['fare'],y=df['class'])
plt.show()

plt.figure()
sns.barplot(x=df['fare'],y=df['embarked'])
plt.show()

plt.figure()
sns.barplot(x=df['survived'],y=df['who'])
plt.show()

plt.figure()
sns.barplot(x=df['survived'],y=df['adult_male'])
plt.show()

plt.figure()
sns.barplot(x=df['survived'],y=df['embark_town'])
plt.show()

plt.figure()
sns.barplot(x=df['survived'],y=df['alive'])
plt.show()

plt.figure()
sns.barplot(x=df['survived'],y=df['alone'])
plt.show()

plt.figure()
sns.barplot(x=df['pclass'],y=df['who'])
plt.show()

plt.figure()
sns.barplot(x=df['pclass'],y=df['adult_male'])
plt.show()

plt.figure()
sns.barplot(x=df['pclass'],y=df['embark_town'])
plt.show()

plt.figure()
sns.barplot(x=df['pclass'],y=df['alive'])
plt.show()

plt.figure()
sns.barplot(x=df['pclass'],y=df['alone'])
plt.show()

plt.figure()
sns.barplot(x=df['age'],y=df['who'])
plt.show()

plt.figure()
sns.barplot(x=df['age'],y=df['adult_male'])
plt.show()

plt.figure()
sns.barplot(x=df['age'],y=df['embark_town'])
plt.show()

plt.figure()
sns.barplot(x=df['age'],y=df['alive'])
plt.show()

plt.figure()
sns.barplot(x=df['age'],y=df['alone'])
plt.show()

plt.figure()
sns.barplot(x=df['sibsp'],y=df['who'])
plt.show()

plt.figure()
sns.barplot(x=df['sibsp'],y=df['adult_male'])
plt.show()

plt.figure()
sns.barplot(x=df['sibsp'],y=df['embark_town'])
plt.show()

plt.figure()
sns.barplot(x=df['sibsp'],y=df['alive'])
plt.show()

plt.figure()
sns.barplot(x=df['sibsp'],y=df['alone'])
plt.show()

plt.figure()
sns.barplot(x=df['parch'],y=df['who'])
plt.show()

plt.figure()
sns.barplot(x=df['parch'],y=df['adult_male'])
plt.show()

plt.figure()
sns.barplot(x=df['parch'],y=df['embark_town'])
plt.show()

plt.figure()
sns.barplot(x=df['parch'],y=df['alive'])
plt.show()

plt.figure()
sns.barplot(x=df['parch'],y=df['alone'])
plt.show()

plt.figure()
sns.barplot(x=df['fare'],y=df['who'])
plt.show()

plt.figure()
sns.barplot(x=df['fare'],y=df['adult_male'])
plt.show()

plt.figure()
sns.barplot(x=df['fare'],y=df['embark_town'])
plt.show()

plt.figure()
sns.barplot(x=df['fare'],y=df['alive'])
plt.show()

plt.figure()
sns.barplot(x=df['fare'],y=df['alive'])
plt.show()

sns.boxplot(x=df['age'])   #numerical     outliers:-devated from data due to errors   1)upper bond 2)lower bond

plt.show()                                  #48 plots in boxplot

sns.boxplot(x=df['survived'])
plt.show()

sns.boxplot(x=df['pclass'])
plt.show()

sns.boxplot(x=df['sibsp'])
plt.show()

sns.boxplot(x=df['parch'])
plt.show()

sns.boxplot(x=df['fare'])
plt.show()

sns.boxplot(x=df['age'],y=df['sex'])
plt.show()

sns.boxplot(x=df['age'],y=df['embarked'])
plt.show()

sns.boxplot(x=df['age'],y=df['class'])
plt.show()

sns.boxplot(x=df['age'],y=df['who'])
plt.show()

sns.boxplot(x=df['age'],y=df['adult_male'])
plt.show()

sns.boxplot(x=df['age'],y=df['embark_town'])
plt.show()

sns.boxplot(x=df['age'],y=df['alive'])
plt.show()

sns.boxplot(x=df['age'],y=df['alone'])
plt.show()

sns.boxplot(x=df['survived'],y=df['sex'])
plt.show()

sns.boxplot(x=df['survived'],y=df['embarked'])
plt.show()

sns.boxplot(x=df['survived'],y=df['class'])
plt.show()

sns.boxplot(x=df['survived'],y=df['who'])
plt.show()

sns.boxplot(x=df['survived'],y=df['adult_male'])
plt.show()

sns.boxplot(x=df['survived'],y=df['embark_town'])
plt.show()

sns.boxplot(x=df['survived'],y=df['alive'])
plt.show()

sns.boxplot(x=df['survived'],y=df['alone'])
plt.show()

sns.boxplot(x=df['pclass'],y=df['sex'])
plt.show()

sns.boxplot(x=df['pclass'],y=df['embarked'])
plt.show()

sns.boxplot(x=df['pclass'],y=df['class'])
plt.show()

sns.boxplot(x=df['pclass'],y=df['who'])
plt.show()

sns.boxplot(x=df['pclass'],y=df['adult_male'])
plt.show()

sns.boxplot(x=df['pclass'],y=df['embark_town'])
plt.show()

sns.boxplot(x=df['pclass'],y=df['alive'])
plt.show()

sns.boxplot(x=df['pclass'],y=df['alone'])
plt.show()

sns.boxplot(x=df['sibsp'],y=df['sex'])
plt.show()

sns.boxplot(x=df['sibsp'],y=df['who'])
plt.show()

sns.boxplot(x=df['sibsp'],y=df['embarked'])
plt.show()

sns.boxplot(x=df['sibsp'],y=df['class'])
plt.show()

sns.boxplot(x=df['sibsp'],y=df['adult_male'])
plt.show()

sns.boxplot(x=df['sibsp'],y=df['embark_town'])
plt.show()

sns.boxplot(x=df['sibsp'],y=df['alive'])
plt.show()

sns.boxplot(x=df['sibsp'],y=df['alone'])
plt.show()

sns.boxplot(x=df['parch'],y=df['sex'])
plt.show()

sns.boxplot(x=df['parch'],y=df['embarked'])
plt.show()

sns.boxplot(x=df['parch'],y=df['class'])
plt.show()

sns.boxplot(x=df['parch'],y=df['who'])
plt.show()

sns.boxplot(x=df['parch'],y=df['adult_male'])
plt.show()

sns.boxplot(x=df['parch'],y=df['embark_town'])
plt.show()

sns.boxplot(x=df['parch'],y=df['alive'])
plt.show()

sns.boxplot(x=df['parch'],y=df['alone'])
plt.show()

sns.boxplot(x=df['parch'],y=df['sex'])
plt.show()

sns.boxplot(x=df['parch'],y=df['embarked'])
plt.show()

import warnings
warnings.filterwarnings('ignore')

sns.boxplot(x=df['parch'],y=df['adult_male'],palette='Pastel2')
plt.show()

sns.boxplot(x=df['parch'],y=df['class'])
plt.show()

sns.boxplot(x=df['parch'],y=df['who'])
plt.show()

sns.boxplot(x=df['parch'],y=df['embark_town'])
plt.show()

sns.boxplot(x=df['parch'],y=df['alive'])
plt.show()

sns.boxplot(x=df['parch'],y=df['alone'])
plt.show()

import seaborn as sns

sns.stripplot(x=df['sex'],y=df['embarked'])
plt.show()

sns.stripplot(x=df['sex'],y=df['class'])
plt.show()

sns.stripplot(x=df['sex'],y=df['who'])
plt.show()

sns.stripplot(x=df['sex'],y=df['adult_male'])
plt.show()

sns.stripplot(x=df['sex'],y=df['embark_town'])
plt.show()

sns.stripplot(x=df['sex'],y=df['alive'])
plt.show()

sns.stripplot(x=df['sex'],y=df['alone'])
plt.show()

sns.stripplot(x=df['embarked'],y=df['sex'])
plt.show()

sns.stripplot(x=df['embarked'],y=df['class'])
plt.show()

sns.stripplot(x=df['embarked'],y=df['who'])
plt.show()

sns.stripplot(x=df['embarked'],y=df['adult_male'])
plt.show()

sns.stripplot(x=df['embarked'],y=df['embark_town'])
plt.show()

sns.stripplot(x=df['embarked'],y=df['alive'])
plt.show()

sns.stripplot(x=df['embarked'],y=df['alone'])
plt.show()

sns.stripplot(x=df['class'],y=df['sex'])
plt.show()

sns.stripplot(x=df['class'],y=df['embarked'])
plt.show()

sns.stripplot(x=df['class'],y=df['who'])
plt.show()

sns.stripplot(x=df['class'],y=df['adult_male'])
plt.show()

sns.stripplot(x=df['class'],y=df['embark_town'])
plt.show()

sns.stripplot(x=df['class'],y=df['alive'])
plt.show()

sns.stripplot(x=df['class'],y=df['alone'])
plt.show()

sns.stripplot(x=df['who'],y=df['sex'])
plt.show()

sns.stripplot(x=df['who'],y=df['embarked'])
plt.show()

sns.stripplot(x=df['who'],y=df['class'])
plt.show()

sns.stripplot(x=df['who'],y=df['class'])
plt.show()

sns.stripplot(x=df['who'],y=df['adult_male'])
plt.show()

sns.stripplot(x=df['who'],y=df['embark_town'])
plt.show()

sns.stripplot(x=df['who'],y=df['alive'])
plt.show()

sns.stripplot(x=df['who'],y=df['alone'])
plt.show()

sns.stripplot(x=df['adult_male'],y=df['sex'])
plt.show()

sns.stripplot(x=df['adult_male'],y=df['embarked'])
plt.show()

sns.stripplot(x=df['adult_male'],y=df['class'])
plt.show()

sns.stripplot(x=df['adult_male'],y=df['who'])
plt.show()

sns.stripplot(x=df['adult_male'],y=df['embark_town'])
plt.show()

sns.stripplot(x=df['adult_male'],y=df['alive'])
plt.show()

sns.stripplot(x=df['adult_male'],y=df['alone'])
plt.show()

sns.stripplot(x=df['embark_town'],y=df['sex'])
plt.show()

sns.stripplot(x=df['embark_town'],y=df['embarked'])
plt.show()

sns.stripplot(x=df['embark_town'],y=df['class'])
plt.show()

sns.stripplot(x=df['embark_town'],y=df['who'])
plt.show()

sns.stripplot(x=df['embark_town'],y=df['adult_male'])
plt.show()

sns.stripplot(x=df['embark_town'],y=df['alive'])
plt.show()

sns.stripplot(x=df['embark_town'],y=df['alone'])
plt.show()

sns.stripplot(x=df['alive'],y=df['sex'])
plt.show()

sns.stripplot(x=df['alive'],y=df['embarked'])
plt.show()

sns.stripplot(x=df['alive'],y=df['class'])
plt.show()

sns.stripplot(x=df['alive'],y=df['who'])
plt.show()

sns.stripplot(x=df['alive'],y=df['adult_male'])
plt.show()

sns.stripplot(x=df['alive'],y=df['embark_town'])
plt.show()

sns.stripplot(x=df['alive'],y=df['alone'])
plt.show()

sns.stripplot(x=df['alone'],y=df['sex'])
plt.show()

sns.stripplot(x=df['alone'],y=df['embarked'])
plt.show()

sns.stripplot(x=df['alone'],y=df['class'])
plt.show()

sns.stripplot(x=df['alone'],y=df['who'])
plt.show()

sns.stripplot(x=df['alone'],y=df['adult_male'])
plt.show()

sns.stripplot(x=df['alone'],y=df['embark_town'])
plt.show()

sns.stripplot(x=df['alone'],y=df['alive'])
plt.show()

plt.figure()
sns.scatterplot(x=df['survived'],y=df['age'],hue=df['sex'])
plt.show()

plt.figure()
sns.scatterplot(x=df['survived'],y=df['sibsp'],hue=df['sex'])
plt.show()

plt.figure()
sns.scatterplot(x=df['survived'],y=df['parch'],hue=df['sex'])
plt.show()

plt.figure()
sns.scatterplot(x=df['survived'],y=df['fare'],hue=df['sex'])
plt.show()

plt.figure()
sns.scatterplot(x=df['survived'],y=df['pclass'],hue=df['sex'])
plt.show()

plt.figure()
sns.scatterplot(x=df['age'],y=df['sibsp'],hue=df['sex'])
plt.show()

plt.figure()
sns.scatterplot(x=df['age'],y=df['parch'],hue=df['sex'])
plt.show()

plt.figure()
sns.scatterplot(x=df['age'],y=df['fare'],hue=df['sex'])
plt.show()

plt.figure()
sns.scatterplot(x=df['age'],y=df['pclass'],hue=df['sex'])
plt.show()

plt.figure()
sns.scatterplot(x=df['sibsp'],y=df['parch'],hue=df['sex'])
plt.show()

plt.figure()
sns.scatterplot(x=df['sibsp'],y=df['fare'],hue=df['sex'])
plt.show()

plt.figure()
sns.scatterplot(x=df['sibsp'],y=df['pclass'],hue=df['sex'])
plt.show()

plt.figure()
sns.scatterplot(x=df['parch'],y=df['fare'],hue=df['sex'])
plt.show()

plt.figure()
sns.scatterplot(x=df['parch'],y=df['pclass'],hue=df['sex'])
plt.show()

plt.figure()
sns.scatterplot(x=df['survived'],y=df['sex'],hue=df['sibsp'])
plt.show()

plt.figure()
sns.scatterplot(x=df['survived'],y=df['sex'],hue=df['parch'])
plt.show()

plt.figure()
sns.scatterplot(x=df['survived'],y=df['sex'],hue=df['fare'])
plt.show()

plt.figure()
sns.scatterplot(x=df['survived'],y=df['sex'],hue=df['pclass'])
plt.show()

plt.figure()
sns.scatterplot(x=df['age'],y=df['sex'],hue=df['sibsp'])
plt.show()

plt.figure()
sns.scatterplot(x=df['age'],y=df['sex'],hue=df['parch'])
plt.show()

plt.figure()
sns.scatterplot(x=df['age'],y=df['sex'],hue=df['fare])
plt.show()

plt.figure()
sns.scatterplot(x=df['age'],y=df['sex'],hue=df['pclass'])
plt.show()

plt.figure()
sns.scatterplot(x=df['sibsp'],y=df['sex'],hue=df['parch'])
plt.show()

plt.figure()
sns.scatterplot(x=df['sibsp'],y=df['sex'],hue=df['fare'])
plt.show()

plt.figure()
sns.scatterplot(x=df['sibsp'],y=df['sex'],hue=df['pclass'])
plt.show()

plt.figure()
sns.scatterplot(x=df['parch'],y=df['sex'],hue=df['fare'])
plt.show()

plt.figure()
sns.scatterplot(x=df['parch'],y=df['sex'],hue=df['pclass'])
plt.show()

plt.figure()
sns.scatterplot(x=df['survived'],y=df['age'],hue=df['alive'])
plt.show()

plt.figure()
sns.scatterplot(x=df['survived'],y=df['sibsp'],hue=df['alive'])
plt.show()

plt.figure()
sns.scatterplot(x=df['survived'],y=df['parch'],hue=df['alive'])
plt.show()

plt.figure()
sns.scatterplot(x=df['survived'],y=df['fare'],hue=df['alive'])
plt.show()

plt.figure()
sns.scatterplot(x=df['survived'],y=df['pclass'],hue=df['alive'])
plt.show()

plt.figure()
sns.scatterplot(x=df['age'],y=df['sibsp'],hue=df['alive'])
plt.show()

plt.figure()
sns.scatterplot(x=df['age'],y=df['parch'],hue=df['alive'])
plt.show()

plt.figure()
sns.scatterplot(x=df['age'],y=df['fare'],hue=df['alive'])
plt.show()

plt.figure()
sns.scatterplot(x=df['age'],y=df['pclass'],hue=df['alive'])
plt.show()

plt.figure()
sns.scatterplot(x=df['sibsp'],y=df['parch'],hue=df['alone'])
plt.show()

plt.figure()
sns.scatterplot(x=df['sibsp'],y=df['fare'],hue=df['alone'])
plt.show()

plt.figure()
sns.scatterplot(x=df['sibsp'],y=df['pclass'],hue=df['alone'])
plt.show()

plt.figure()
sns.scatterplot(x=df['fare'],y=df['pclass'],hue=df['alone'])
plt.show()

plt.figure()
sns.scatterplot(x=df['survived'],y=df['age'],hue=df['adult_male'])
plt.show()

plt.figure()
sns.scatterplot(x=df['survived'],y=df['sibsp'],hue=df['adult_male'])
plt.show()

plt.figure()
sns.scatterplot(x=df['survived'],y=df['parch'],hue=df['adult_male'])
plt.show()

plt.figure()
sns.scatterplot(x=df['survived'],y=df['fare'],hue=df['adult_male'])
plt.show()

plt.figure()
sns.scatterplot(x=df['survived'],y=df['pclass'],hue=df['adult_male'])
plt.show()

plt.figure()
sns.scatterplot(x=df['age'],y=df['sibsp'],hue=df['adult_male'])
plt.show()

plt.figure()
sns.scatterplot(x=df['age'],y=df['parch'],hue=df['adult_male'])
plt.show()

plt.figure()
sns.scatterplot(x=df['age'],y=df['fare'],hue=df['adult_male'])
plt.show()

plt.figure()
sns.scatterplot(x=df['age'],y=df['pclass'],hue=df['adult_male'])
plt.show()

plt.figure()
sns.scatterplot(x=df['sibsp'],y=df['parch'],hue=df['adult_male'])
plt.show()

plt.figure()
sns.scatterplot(x=df['sibsp'],y=df['fare'],hue=df['adult_male'])
plt.show()

plt.figure()
sns.scatterplot(x=df['sibsp'],y=df['pclass'],hue=df['adult_male'])
plt.show()

plt.figure()
sns.scatterplot(x=df['sibsp'],y=df['fare'],hue=df['adult_male'])
plt.show()

plt.figure()
sns.scatterplot(x=df['sibsp'],y=df['pclass'],hue=df['adult_male'])
plt.show()

plt.figure()
sns.scatterplot(x=df['parch'],y=df['fare'],hue=df['adult_male'])
plt.show()

plt.figure()
sns.scatterplot(x=df['parch'],y=df['pclass'],hue=df['adult_male'])
plt.show()

plt.figure()
sns.scatterplot(x=df['fare'],y=df['pclass'],hue=df['adult_male'])
plt.show()

plt.figure()
sns.scatterplot(x=df['survived'],y=df['age'],hue=df['embarked'])
plt.show()

plt.figure()
sns.scatterplot(x=df['survived'],y=df['sibsp'],hue=df['embarked'])
plt.show()

plt.figure()
sns.scatterplot(x=df['survived'],y=df['parch'],hue=df['embarked'])
plt.show()

plt.figure()
sns.scatterplot(x=df['survived'],y=df['fare'],hue=df['embarked'])
plt.show()

plt.figure()
sns.scatterplot(x=df['survived'],y=df['pclass'],hue=df['embarked'])
plt.show()

plt.figure()
sns.scatterplot(x=df['age'],y=df['sibsp'],hue=df['embarked'])
plt.show()

plt.figure()
sns.scatterplot(x=df['age'],y=df['parch'],hue=df['embarked'])
plt.show()

plt.figure()
sns.scatterplot(x=df['age'],y=df['fare'],hue=df['embarked'])
plt.show()

plt.figure()
sns.scatterplot(x=df['age'],y=df['pclass'],hue=df['embarked'])
plt.show()

plt.figure()
sns.scatterplot(x=df['sibsp'],y=df['parch'],hue=df['embarked'])
plt.show()

plt.figure()
sns.scatterplot(x=df['sibsp'],y=df['fare'],hue=df['embarked'])
plt.show()

plt.figure()
sns.scatterplot(x=df['sibsp'],y=df['pclass'],hue=df['embarked'])
plt.show()

plt.figure()
sns.scatterplot(x=df['parch'],y=df['fare'],hue=df['embarked'])
plt.show()

plt.figure()
sns.scatterplot(x=df['parch'],y=df['pclass'],hue=df['embarked'])
plt.show()

plt.figure()
sns.scatterplot(x=df['fare'],y=df['pclass'],hue=df['embarked'])
plt.show()

plt.figure()
sns.scatterplot(x=df['survived'],y=df['age'],hue=df['who'])
plt.show()

plt.figure()
sns.scatterplot(x=df['survived'],y=df['sibsp'],hue=df['who'])
plt.show()

plt.figure()
sns.scatterplot(x=df['survived'],y=df['parch'],hue=df['who'])
plt.show()

plt.figure()
sns.scatterplot(x=df['survived'],y=df['fare'],hue=df['who])
plt.show()

plt.figure()
sns.scatterplot(x=df['survived'],y=df['pclass'],hue=df['who'])
plt.show()

plt.figure()
sns.scatterplot(x=df['age'],y=df['sibsp'],hue=df['who'])
plt.show()

plt.figure()
sns.scatterplot(x=df['age'],y=df['parch'],hue=df['who'])
plt.show()

plt.figure()
sns.scatterplot(x=df['age'],y=df['fare'],hue=df['who'])
plt.show()

plt.figure()
sns.scatterplot(x=df['age'],y=df['pclass'],hue=df['who'])
plt.show()

plt.figure()
sns.scatterplot(x=df['sibsp'],y=df['parch'],hue=df['who'])
plt.show()

plt.figure()
sns.scatterplot(x=df['sibsp'],y=df['fare'],hue=df['who'])
plt.show()

plt.figure()
sns.scatterplot(x=df['sibsp'],y=df['pclass'],hue=df['who'])
plt.show()

plt.figure()
sns.scatterplot(x=df['parch'],y=df['fare'],hue=df['who'])
plt.show()

plt.figure()
sns.scatterplot(x=df['parch'],y=df['pclass'],hue=df['who'])
plt.show()

plt.figure()
sns.scatterplot(x=df['fare'],y=df['pclass'],hue=df['who'])
plt.show()

plt.figure()
sns.barplot(x=df['survived'],y=df['age'],hue=df['sex'])
plt.show()

plt.figure()
sns.barplot(x=df['survived'],y=df['sibsp'],hue=df['sex'])
plt.show()

plt.figure()
sns.barplot(x=df['survived'],y=df['parch'],hue=df['sex'])
plt.show()

plt.figure()
sns.barplot(x=df['survived'],y=df['fare'],hue=df['sex'])
plt.show()

plt.figure()
sns.barplot(x=df['survived'],y=df['pclass'],hue=df['sex'])
plt.show()

